model_parameters:
  model_name: "~/models/introspection/qwen-2.5-7b-it-loving"
  revision: "main"
  dtype: "bfloat16"
  tensor_parallel_size: 4
  data_parallel_size: 1
  pipeline_parallel_size: 1
  gpu_memory_utilization: 0.9
  max_model_length: 8192
  swap_space: 4
  seed: 123456
  trust_remote_code: False
  add_special_tokens: True
  multichoice_continuations_start_space: False
  pairwise_tokenization: False
  subfolder: null
  max_num_seqs: 2048
  max_num_batched_tokens: 65536
  is_async: false
  generation_parameters:
    presence_penalty: 0.0
    repetition_penalty: 1.05
    frequency_penalty: 0.0
    temperature: 0.7
    top_k: 20
    min_p: 0.0
    top_p: 0.8
    seed: 123456
    stop_tokens: null
    max_new_tokens: 2048
    min_new_tokens: 0
